source 'http://rubygems.org'
gem 'rails', '3.0.8'
gem 'sqlite3'
gem 'rspec-rails', '2.6.1', :group => [:development, :test]
gem 'factory_girl_rails', '1.1.beta1', :group => :test
gem 'cucumber-rails', '0.5.1', :group => :test
gem 'capybara', '1.0.0.beta1', :group => :test
gem 'database_cleaner', '0.6.7', :group => :test
gem 'launchy', '0.4.0', :group => :test
gem 'devise', '1.3.4'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
